baseURL = 'https://msavage314.github.io/My-Blog/'
languageCode = 'en-us'
title = "Michael Savage's Blog"
theme = 'hugo-theme-stack'

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true

[params.sidebar]
emoji = "üç•"
subtitle = "Random projects, code, and ideas"

[[params.sidebar.avatar]]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
math = false
readingTime = true

[params.comments]
enabled = false

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = -90
